### PR TITLE
 Upgrade to fyne 2.5.2 

### PR DESCRIPTION
**Pull request by xypwn**

### CODE REVIEW

**Comment by refaktor** [comment]
Thank you for the update!

**Comment by refaktor** [comment]
Hm ... rye got reverted back to 0.0.25. No problem, just not sure how it happened ... wouldn't it be a conflict in git?

**Comment by xypwn** [comment]
Ohh, that must have been a mistake. I probably relied on the replace directive, which points to the most recent version of Rye, so upgrading to that should work just as well.

**Comment by refaktor** [comment]
No problem ... just wasn't sure if something got lost or I didn't commit ... but I see it in diff. :+1:

**Pull request merged**
